const catchAsync = require("../utils/catchAsync");

exports.globalErrorHandler = catchAsync(async (next) => {});
